### ISSUE TITLE
Update labels in CDDL

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/careful-resume#24]
The current CDDL does not align with the specification:

OLD:
previous_congestion_window: uint,
previous_rtt: float32
NEW:
saved_cwnd: uint,
saved_rtt: float32

**Comment by gorryfair** [comment]
Not quite, the words 'previous_congestion_window' do not appear, if there's strong desire for 'saved_congestion_window' that's fine with me a comment can always say this is the same as 'saved_cwnd'. 

I think 'saved_rtt' is fine,

Gorry

**Comment by TheEnbyperor** [comment]
For consistency I'd prefer both variables to start `saved_'; and I don't think there's a point in trying to cut down on variable name lengths (at the possible detriment of ease of understanding) as QLog files are already large in size and gzip (or other) compression will deal with this fine.
