### ISSUE TITLE
CR_Mark is used in the Qlog CDDL

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/careful-resume#26]
The proposed CDDL uses the internal variable "CR_Mark", which could be useful for understanding the exact state of the sender.

However, this variable (based on cwnd) is not explicitly described in the body of the specification. I suggest we look whether this is needed in the Qlog, and if so, how this relates to the state machine in the text and therefore what ought to be said.

**Comment by TheEnbyperor** [comment]
From experience debugging my implementation it is a useful metric to include, so a fuller description of what it is seems sensible.

**Comment by gorryfair** [comment]
CDDL updated by AC
