### ISSUE TITLE
Per transport or per CC algorithm?

### ISSUE THREAD

**Issue by huitema** [tsvwg/careful-resume#28]
The idea of having explicit states like "reconnaissance" or "careful retreat" is attractive, but I think it confuses what is generic and could be done at the transport level, and what is specific to congestion control algorithms. The general idea is to remember previous settings of the congestion control algorithm, and then to apply those settings safely. For example:

1) The concept of reconnaissance is generic. This is a key part of the draft: evaluate whether the previously remember values are still valid, and can be safely applied. It can be implemented in a generic way: quickly evaluate that the IP addresses match, and that the RTT is "in the ballpark". There is no need to encumber each CC algorithm with that.

2) The actual values remembered are protocol specific. Reno remembers the CWIN. Hystart also remembers the CWIN, but should probably also remember RTT information. (Cubic uses Hystart.) BBR needs to remember the RTTMin, the evaluated data rate, and typically derives the CWIN from that.

3) The execution of the trial phase is algorithm specific. Reno looks for packet losses, and maybe for ECN marks. Cubic uses Hystart, which monitors transmission delays, losses and possibly ECN marks. BBR measures the data rate, but also reacts to packet losses and ECN marks. These three algorithm do not react in the same way.

4) The trial phase is not fundamentally different from the slow start, hystart or startup. All these algorithms can be modified to incorporate remembered values, as in careful resume, or rapid evaluation, such as for example chirping. All these algorithms have an idea of "oops, overshot the network capacity". They also have a way to recover from that -- BBR's "draining" state is very much the same thing as "careful retreat".

The state machine presented in the draft should be taken with a huge grain of salt -- it looks good on paper, but does not match the structure of practical implementations. It would be more productive to have section specifying the changes to specific algorithms, or maybe separate drafts for each algorithm.

**Comment by gorryfair** [comment]
I agree with 1 and 2, in that the CC determines the "retreat", but I think the spec says that. 
- I don't see why you say: "The trial phase is not fundamentally different from the slow start, hystart or startup", I think it is.  It is not good practice to push hard against other (potential)assuming that the previous rate was good. That's not a sociable CC - it's a test to whether the sharing CCs are polite and will get out of the way.

- I am also quite unsure with an assertion that  "BBR measures the data rate", is likely very problematic in this specific context:  If we had a concrete BBR Spec, it would be easier for another RFC to say more.
-

**Comment by huitema** [comment]
The signals that CC use to say "oops, I pushed too hard" are pretty much the same whether you use careful resume or not -- packet losses, delay increases, ECN marks, or, in the case of BBR a data delivery rate that does not increase despite the pushes. I think that the one interesting issue in the draft is the way the CC algorithm exits its startup phase. Clearly, in the case of RENO, if the controller tried to set the BDP to 1000 packets and got negative feedback, it should not fall back to CWIN/2.

**Comment by huitema** [comment]
For BBR, the sequence of event will be:

* based on previous measurements, during startup, the controller tries to send at 200Mbps.
* opps, ECN received. enter Drain.
* some of the packets sent get acked, and during Drain the controller measures the delivery rate as 15Mbps.
* once the queue is drained, the controller enters probe BW with a delivery rate set at 15Mbps.

I actually implemented that in Picoquic.

**Comment by gorryfair** [comment]
Did you have analysis of the harm that causes to other flows that started later, and hence when the  impact when the estimation was way too large? It would be very useful to understand what metrics/tooling was used to judge that whether a method is "safe" or "antisocial" (whatever terms).

**Comment by huitema** [comment]
I think the harm is binary -- either you create a big overflow or you don't. Assuming that the network buffers carry 2*BDP, it is probably safe to start with 1/2 the remembered value, because the packets in transit will create a queue and will not induce losses. But yes, there is always a risk of creating a local peak.

**Comment by huitema** [comment]
By definition, the "resume" function will grow the transmission parameters more quickly than the regular "slow start" process. So we can always make the argument that doing that is antisocial. We could also argue that an hypothetical "slower start" process that only grew the window by 25% or 50% per RTT would be "less antisocial" than the current "slow start".

I think that my unease with the current version is because instead of static the design parameters, the draft jumps from the motivation to the specification of an algorithm which is deeply tied to Reno. But fine, that's on me. I will try to write a section explaining the principle of the solution, so designers of future CC algorithms can adopt it. Then I will propose renaming the current algorithm to make it clear that this is an example of implementation based on Reno.

**Comment by gorryfair** [comment]
I don't see the spec as tied to Reno. We have implemented in Cubic and Reno, and are playing with BBR. I suspect that when it is discovered that an unvalidated path has congestion, a sender needs a different reaction to that typical for loss recovery (aka, a Safe Retreat). The idea of rate-halving in Safe Retreat is for stability, not for optimisation of throughput. After draining the path in an RTT and a lower restart, each CC algorithm will find its own way to a new rate.

However, I do agree it would be useful to insert a section that talks about the design space - some start of this did appear in the earlier revisions, it would be likely good to re-introduce. Would you like to try a PR based on rev -08 (which was just made).

**Comment by gorryfair** [comment]
Merged a PR that is thought to address.
