### ISSUE TITLE
Packets vs. bytes?

### ISSUE THREAD

**Issue by joergdeutschmann-i7** [tsvwg/careful-resume#29]
Should 
```
pipesize: uint,
cr_mark: uint,
congestion_window: uint,
ssthresh: uint
```
be specified if it is in packets or bytes?

The Example sections uses packets...

**Comment by TheEnbyperor** [comment]
Given all other QLog variables for CC are in bytes so these should also be in bytes. The examples section should be corrected to use bytes.

**Comment by joergdeutschmann-i7** [comment]
IMHO the qlog variables should be in bytes, which suits real implementations.
However, the examples should use packets, which is way easier for mental arithmetic.
Maybe one could add one sentence to say that in the examples packets are used on purpose, while qlog specifies bytes.
